import React, { useState } from 'react';
import './App.css';
import proto from './proto/gen/main_pb.js';
import grpc from './proto/gen/main_grpc_web_pb.js';
import HealthCheck from './rpcs/HealthCheck.jsx';
import GetOriginalURL from './rpcs/GetOriginalURL.jsx';
import IncrementClick from './rpcs/IncrementClick.jsx';
import GetURLStats from './rpcs/GetURLStats.jsx';
import UpdateURL from './rpcs/UpdateURL.jsx';
import DeleteURL from './rpcs/DeleteURL.jsx';
import ListAllURLs from './rpcs/ListAllURLs.jsx';

// Create a promise-based client. Set VITE_API_HOST in .env or default to localhost
const GRPC_HOST = import.meta.env.VITE_API_HOST || 'http://localhost:8081';
// Root to use for clickable short links (so frontend dev server origin doesn't get used).
// Set VITE_SHORT_ROOT in .env to override (example: http://localhost:8080)
const SHORT_ROOT = import.meta.env.VITE_SHORT_ROOT || 'http://localhost:8080';
const client = new grpc.UrlShortenerPromiseClient(GRPC_HOST);

export default function App() {
	const [selectedRpc, setSelectedRpc] = useState(null);

	function goBack() {
		setSelectedRpc(null);
	}

	const [originalUrl, setOriginalUrl] = useState('');
	const [expireSeconds, setExpireSeconds] = useState('0');
	const [shortUrl, setShortUrl] = useState(null);
	const [shortId, setShortId] = useState(null);
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState(null);

	async function handleSubmit(e) {
		e.preventDefault();
		setError(null);
		setShortUrl(null);
		setShortId(null);

		if (!originalUrl || originalUrl.trim() === '') {
			setError('Please enter a URL to shorten.');
			return;
		}

		const req = new proto.ShortenURLRequest();
		req.setOriginalUrl(originalUrl.trim());
		const secs = Number(expireSeconds) || 0;
		if (secs > 0) req.setExpireInSeconds(secs);

		setLoading(true);
		try {
			const resp = await client.shortenURL(req);
			// response has getters generated by proto
			const sUrl = resp.getShortUrl ? resp.getShortUrl() : null;
			const sId = resp.getShortId ? resp.getShortId() : null;
			// Prefer building a frontend link using the shortId so clicking opens
			// e.g. http://localhost:8080/cj4hrZ which the backend handles and redirects.
			let displayUrl = sUrl;
			if (sId) {
				// Use configured SHORT_ROOT (VITE_SHORT_ROOT) or default to http://localhost:8080
				try {
					displayUrl = `${SHORT_ROOT}/${sId}`;
				} catch (e) {
					// fallback to server-provided URL if anything goes wrong
					displayUrl = sUrl;
				}
			}
			setShortUrl(displayUrl);
			setShortId(sId);
		} catch (err) {
			// grpc-web RpcError object has code and message
			const msg = (err && err.message) ? `${err.message}` : String(err);
			setError(msg);
			// also log full error for dev
			// eslint-disable-next-line no-console
			console.error('ShortenURL error', err);
		} finally {
			setLoading(false);
		}
	}

	return (
		<div className="app-container">
			<header className="navbar">
				<div className="brand">URL Shortener</div>
				<nav className="nav-actions">
					<button type="button" className="btn btn-outline" onClick={() => setSelectedRpc(null)}>Home</button>
					<button type="button" className="btn btn-outline" onClick={() => setSelectedRpc('health')}>Health</button>
					<button type="button" className="btn btn-outline" onClick={() => setSelectedRpc('list')}>List</button>
				</nav>
			</header>

			{/* RPC navigation buttons */}
			<div className="toolbar">
				<button type="button" className="btn" onClick={() => setSelectedRpc('health')}>HealthCheck</button>
				<button type="button" className="btn" onClick={() => setSelectedRpc('get')}>GetOriginalURL</button>
				<button type="button" className="btn" onClick={() => setSelectedRpc('inc')}>IncrementClick</button>
				<button type="button" className="btn" onClick={() => setSelectedRpc('stats')}>GetURLStats</button>
				<button type="button" className="btn" onClick={() => setSelectedRpc('update')}>UpdateURL</button>
				<button type="button" className="btn" onClick={() => setSelectedRpc('delete')}>DeleteURL</button>
				<button type="button" className="btn" onClick={() => setSelectedRpc('list')}>ListAllURLs</button>
			</div>

			{/* Render chosen RPC component (pass client, proto, goBack) */}
			{selectedRpc === 'health' && <HealthCheck client={client} proto={proto} goBack={goBack} />}
			{selectedRpc === 'get' && <GetOriginalURL client={client} proto={proto} goBack={goBack} />}
			{selectedRpc === 'inc' && <IncrementClick client={client} proto={proto} goBack={goBack} />}
			{selectedRpc === 'stats' && <GetURLStats client={client} proto={proto} goBack={goBack} />}
			{selectedRpc === 'update' && <UpdateURL client={client} proto={proto} goBack={goBack} />}
			{selectedRpc === 'delete' && <DeleteURL client={client} proto={proto} goBack={goBack} />}
			{selectedRpc === 'list' && <ListAllURLs client={client} proto={proto} goBack={goBack} />}

			{/* If no rpc selected, show the existing shorten form */}
			{selectedRpc === null && (
			<>
				<section className="hero">
					<h1>Shorten links. Share faster.</h1>
					<p className="muted">Create clean short links with analytics and management via gRPC‑Web.</p>
				</section>

				<div className="card">
					<div className="card-header">Create a short link</div>
					<div className="card-body">
						<form onSubmit={handleSubmit} className="form-grid">
							<label className="label">
								<span>Long URL</span>
								<input
									className="input"
									type="text"
									value={originalUrl}
									onChange={(e) => setOriginalUrl(e.target.value)}
									placeholder="https://example.com/very/long/path"
								/>
							</label>

							<label className="label inline">
								<span>Expire in seconds (optional)</span>
								<input
									className="input input-number"
									type="number"
									min="0"
									value={expireSeconds}
									onChange={(e) => setExpireSeconds(e.target.value)}
								/>
							</label>

							<div>
								<button type="submit" className="btn btn-primary" disabled={loading}>
									{loading ? 'Shortening…' : 'Shorten URL'}
								</button>
							</div>
						</form>
					</div>
				</div>
			</>
			)}

			<div className="messages">
				{error && (
					<div className="error">
						<strong>Error:</strong> {error}
					</div>
				)}

				{shortUrl && (
					<div className="result">
						<h3>Shortened URL</h3>
						<p>
							<a href={shortUrl} target="_blank" rel="noreferrer">{shortUrl}</a>
						</p>
						{shortId && <p><small>id: {shortId}</small></p>}
					</div>
				)}
			</div>

			<hr className="divider" />
			<p className="muted">
				Using gRPC host: <code>{GRPC_HOST}</code>
			</p>
		</div>
	);
}
