import React, { useState } from 'react';
import proto from './proto/gen/main_pb.js';
import grpc from './proto/gen/main_grpc_web_pb.js';
import HealthCheck from './rpcs/HealthCheck.jsx';
import GetOriginalURL from './rpcs/GetOriginalURL.jsx';
import IncrementClick from './rpcs/IncrementClick.jsx';
import GetURLStats from './rpcs/GetURLStats.jsx';
import UpdateURL from './rpcs/UpdateURL.jsx';
import DeleteURL from './rpcs/DeleteURL.jsx';
import ListAllURLs from './rpcs/ListAllURLs.jsx';

// Create a promise-based client. Set VITE_API_HOST in .env or default to localhost
const GRPC_HOST = import.meta.env.VITE_API_HOST || 'http://localhost:8081';
// Root to use for clickable short links (so frontend dev server origin doesn't get used).
// Set VITE_SHORT_ROOT in .env to override (example: http://localhost:8080)
const SHORT_ROOT = import.meta.env.VITE_SHORT_ROOT || 'http://localhost:8080';
const client = new grpc.UrlShortenerPromiseClient(GRPC_HOST);

export default function App() {
	const [selectedRpc, setSelectedRpc] = useState(null);

	function goBack() {
		setSelectedRpc(null);
	}

	const [originalUrl, setOriginalUrl] = useState('');
	const [expireSeconds, setExpireSeconds] = useState('0');
	const [shortUrl, setShortUrl] = useState(null);
	const [shortId, setShortId] = useState(null);
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState(null);

	async function handleSubmit(e) {
		e.preventDefault();
		setError(null);
		setShortUrl(null);
		setShortId(null);

		if (!originalUrl || originalUrl.trim() === '') {
			setError('Please enter a URL to shorten.');
			return;
		}

		const req = new proto.ShortenURLRequest();
		req.setOriginalUrl(originalUrl.trim());
		const secs = Number(expireSeconds) || 0;
		if (secs > 0) req.setExpireInSeconds(secs);

		setLoading(true);
		try {
			const resp = await client.shortenURL(req);
			// response has getters generated by proto
			const sUrl = resp.getShortUrl ? resp.getShortUrl() : null;
			const sId = resp.getShortId ? resp.getShortId() : null;
			// Prefer building a frontend link using the shortId so clicking opens
			// e.g. http://localhost:8080/cj4hrZ which the backend handles and redirects.
			let displayUrl = sUrl;
			if (sId) {
				// Use configured SHORT_ROOT (VITE_SHORT_ROOT) or default to http://localhost:8080
				try {
					displayUrl = `${SHORT_ROOT}/${sId}`;
				} catch (e) {
					// fallback to server-provided URL if anything goes wrong
					displayUrl = sUrl;
				}
			}
			setShortUrl(displayUrl);
			setShortId(sId);
		} catch (err) {
			// grpc-web RpcError object has code and message
			const msg = (err && err.message) ? `${err.message}` : String(err);
			setError(msg);
			// also log full error for dev
			// eslint-disable-next-line no-console
			console.error('ShortenURL error', err);
		} finally {
			setLoading(false);
		}
	}

	return (
		<div style={{maxWidth: 720, margin: '40px auto', fontFamily: 'system-ui, sans-serif'}}>
			{/* RPC navigation buttons */}
			<div style={{display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 18}}>
				<button type="button" onClick={() => setSelectedRpc('health')} style={{padding: '6px 10px'}}>
					HealthCheck
				</button>
				<button type="button" onClick={() => setSelectedRpc('get')} style={{padding: '6px 10px'}}>
					GetOriginalURL
				</button>
				<button type="button" onClick={() => setSelectedRpc('inc')} style={{padding: '6px 10px'}}>
					IncrementClick
				</button>
				<button type="button" onClick={() => setSelectedRpc('stats')} style={{padding: '6px 10px'}}>
					GetURLStats
				</button>
				<button type="button" onClick={() => setSelectedRpc('update')} style={{padding: '6px 10px'}}>
					UpdateURL
				</button>
				<button type="button" onClick={() => setSelectedRpc('delete')} style={{padding: '6px 10px'}}>
					DeleteURL
				</button>
				<button type="button" onClick={() => setSelectedRpc('list')} style={{padding: '6px 10px'}}>
					ListAllURLs
				</button>
			</div>

			{/* Render chosen RPC component (pass client, proto, goBack) */}
			{selectedRpc === 'health' && <HealthCheck client={client} proto={proto} goBack={goBack} />}
			{selectedRpc === 'get' && <GetOriginalURL client={client} proto={proto} goBack={goBack} />}
			{selectedRpc === 'inc' && <IncrementClick client={client} proto={proto} goBack={goBack} />}
			{selectedRpc === 'stats' && <GetURLStats client={client} proto={proto} goBack={goBack} />}
			{selectedRpc === 'update' && <UpdateURL client={client} proto={proto} goBack={goBack} />}
			{selectedRpc === 'delete' && <DeleteURL client={client} proto={proto} goBack={goBack} />}
			{selectedRpc === 'list' && <ListAllURLs client={client} proto={proto} goBack={goBack} />}

			{/* If no rpc selected, show the existing shorten form */}
			{selectedRpc === null && (
			<>
				<h1>URL Shortener — gRPC-web demo</h1>

				<form onSubmit={handleSubmit} style={{display: 'grid', gap: 12}}>
				<label>
					Long URL
					<input
						type="text"
						value={originalUrl}
						onChange={(e) => setOriginalUrl(e.target.value)}
						placeholder="https://example.com/very/long/path"
						style={{width: '100%', padding: 8, marginTop: 6}}
					/>
				</label>

				<label>
					Expire in seconds (optional)
					<input
						type="number"
						min="0"
						value={expireSeconds}
						onChange={(e) => setExpireSeconds(e.target.value)}
						style={{width: 200, padding: 8, marginTop: 6}}
					/>
				</label>

				<div>
					<button type="submit" disabled={loading} style={{padding: '8px 14px'}}>
						{loading ? 'Shortening…' : 'Shorten URL'}
					</button>
				</div>
			</form>
			</>
			)}

			<div style={{marginTop: 20}}>
				{error && (
					<div style={{color: 'crimson'}}>
						<strong>Error:</strong> {error}
					</div>
				)}

				{shortUrl && (
					<div>
						<h3>Shortened URL</h3>
						<p>
							<a href={shortUrl} target="_blank" rel="noreferrer">{shortUrl}</a>
						</p>
						{shortId && <p><small>id: {shortId}</small></p>}
					</div>
				)}
			</div>

			<hr style={{marginTop: 32}} />
			<p style={{color: '#666'}}>
				Using gRPC host: <code>{GRPC_HOST}</code>
			</p>

			<p style={{color: '#666'}}>
				Tip: if your backend is gRPC+grpc-web behind a proxy (envoy or grpc-gateway), make sure CORS and grpc-web proxying are configured.
			</p>
		</div>
	);
}
